stages:
  - validate
  - security

default:
  image: node:24.15.0-alpine
  cache:
    paths:
      - .npm/
  before_script:
    - node --version
    - npm --version
    - npm ci --cache .npm --prefer-offline --ignore-scripts

typecheck:
  stage: validate
  script:
    - npx tsc --noEmit
  only:
    - develop

audit:
  stage: security
  script:
    - npm audit --audit-level=high
  only:
    - develop
